.PHONY: clean All

All:
	@echo "----------Building project:[ BDDOne - Debug ]----------"
	@cd "BDDOne" && "$(MAKE)" -f  "BDDOne.mk"
clean:
	@echo "----------Cleaning project:[ BDDOne - Debug ]----------"
	@cd "BDDOne" && "$(MAKE)" -f  "BDDOne.mk" clean
